name = "news-state"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "NEWS_STATE"
id = "b60c244e12b44a688ff29226b43be030"
preview_id = "todo_replace_with_preview_id"

[triggers]
crons = ["*/15 * * * *"] # Every 15 minutes



[observability.logs]
enabled = true
invocation_logs = true

